# Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

# Data

In [2]:
df = pd.read_csv('C:\Saurabh\My phone\datasets\creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

# Balancing dataset

In [38]:
df.groupby('Class').V1.agg('count')


Class
0    284315
1       492
Name: V1, dtype: int64

In [4]:
inputs = df.drop('Class', axis = 1)
targets = df['Class']

In [5]:
num_one_targets = int(targets.sum())
zero_counter = 0
indices_to_remove = []

for i in range(targets.shape[0]):
    if targets[i]==0:
        zero_counter +=1
        if zero_counter > num_one_targets:
            indices_to_remove.append(i)

In [6]:
len(indices_to_remove)

283823

In [7]:
print(targets.shape)
print(inputs.shape)
print(np.shape(indices_to_remove))

(284807,)
(284807, 30)
(283823,)


In [8]:
inputs_equal_prior = inputs.drop(indices_to_remove, axis = 0)

In [9]:
inputs_equal_prior.shape

(984, 30)

In [10]:
targets_equal_priors = targets.drop(indices_to_remove, axis = 0)

In [11]:
targets_equal_priors.shape

(984,)

# Training dataset

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(inputs_equal_prior, targets_equal_priors,\
                                                   test_size = 0.2)

# Classifiers 

### Logistic regression

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
log = LogisticRegression()

In [16]:
log.fit(x_train, y_train)

C:\Users\Saurabh\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
y_pred_log = log.predict(x_test)

In [18]:
log.score(x_test, y_test)

1.0

### Decision tree

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
dec = DecisionTreeClassifier()

In [21]:
dec.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [22]:
y_pred_dec = dec.predict(x_test)

In [23]:
dec.score(x_test, y_test)

1.0

### Random forest

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rnd = RandomForestClassifier()

In [26]:
rnd.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [27]:
y_pred_rnd = rnd.predict(x_test)

In [28]:
rnd.score(x_test, y_test)

1.0

## Confusion matrix

In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
cm_log = confusion_matrix(y_test, y_pred_log)
cm_dec = confusion_matrix(y_test, y_pred_dec)
cm_rnd = confusion_matrix(y_test, y_pred_rnd)

In [31]:
print(cm_log)
print(cm_dec)
print(cm_rnd)

[[ 96   0]
 [  0 101]]
[[ 96   0]
 [  0 101]]
[[ 96   0]
 [  0 101]]


## Classification report

In [32]:
from sklearn.metrics import classification_report

In [33]:
print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        96
           1       1.00      1.00      1.00       101

    accuracy                           1.00       197
   macro avg       1.00      1.00      1.00       197
weighted avg       1.00      1.00      1.00       197



In [34]:
print(classification_report(y_test, y_pred_dec))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        96
           1       1.00      1.00      1.00       101

    accuracy                           1.00       197
   macro avg       1.00      1.00      1.00       197
weighted avg       1.00      1.00      1.00       197



In [35]:
print(classification_report(y_test, y_pred_rnd))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        96
           1       1.00      1.00      1.00       101

    accuracy                           1.00       197
   macro avg       1.00      1.00      1.00       197
weighted avg       1.00      1.00      1.00       197



As we can see all the models show us the perfect results but I will suggest to use Random forest classifier because it is the most reliable among these.