# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

# Data

In [2]:
df = pd.read_csv("C:\Saurabh\My phone\datasets\Heart disease\heart.csv")

In [3]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [44]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [45]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

# Inputs and targets

In [4]:
inputs = df.drop('target', axis = 1)
targets = df['target']

# Balancing dataset

In [5]:
df.groupby('target').target.agg('count')

target
0    138
1    165
Name: target, dtype: int64

In [6]:
zero_count = int(targets.shape[0] - targets.sum())
one_count = 0
indices_to_remove = []

for i in range(targets.shape[0]):
    if targets[i] == 1:
        one_count += 1
        if one_count > zero_count:
            indices_to_remove.append(i)

In [7]:
inputs_equal_priors = inputs.drop(indices_to_remove, axis = 0)
targets_equal_priors = targets.drop(indices_to_remove, axis = 0)

In [8]:
targets_equal_priors.shape

(276,)

# train-test split

In [9]:
from sklearn.model_selection import train_test_split

In [31]:
x_train, x_test, y_train, y_test = train_test_split(inputs_equal_priors, targets_equal_priors,\
                                                   test_size = 0.2)

# Classifiers

### Logistic regression

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
log = LogisticRegression()

In [32]:
log.fit(x_train, y_train)

C:\Users\Saurabh\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
log.score(x_test, y_test)

0.8392857142857143

### Decision tree

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
dec = DecisionTreeClassifier()

In [34]:
dec.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [35]:
dec.score(x_test, y_test)

0.7142857142857143

### Random forest

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rnd = RandomForestClassifier()

In [36]:
rnd.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [37]:
rnd.score(x_test, y_test)

0.8392857142857143

In [38]:
y_pred_rnd = rnd.predict(x_test)

In [24]:
from sklearn.model_selection import cross_val_score

In [39]:
cross_val = cross_val_score(rnd, x_train, y_train, cv = 5)

In [40]:
cross_val

array([0.86363636, 0.84090909, 0.90909091, 0.72727273, 0.81818182])

### Confusion matrix

In [46]:
from sklearn.metrics import confusion_matrix

In [42]:
y_pred_log = log.predict(x_test)
y_pred_dec = dec.predict(x_test)

In [47]:
cm_log = confusion_matrix(y_test, y_pred_log)
cm_dec = confusion_matrix(y_test, y_pred_dec)
cm_rnd = confusion_matrix(y_test, y_pred_rnd)

In [48]:
print(cm_log)
print(cm_dec)
print(cm_rnd)

[[24  7]
 [ 2 23]]
[[22  9]
 [ 7 18]]
[[23  8]
 [ 1 24]]


### Classification report

In [27]:
from sklearn.metrics import classification_report

In [43]:
print(classification_report(y_test, y_pred_log))
print(classification_report(y_test, y_pred_dec))

              precision    recall  f1-score   support

           0       0.92      0.77      0.84        31
           1       0.77      0.92      0.84        25

    accuracy                           0.84        56
   macro avg       0.84      0.85      0.84        56
weighted avg       0.85      0.84      0.84        56

              precision    recall  f1-score   support

           0       0.76      0.71      0.73        31
           1       0.67      0.72      0.69        25

    accuracy                           0.71        56
   macro avg       0.71      0.71      0.71        56
weighted avg       0.72      0.71      0.72        56



In [41]:
print(classification_report(y_test, y_pred_rnd))

              precision    recall  f1-score   support

           0       0.96      0.74      0.84        31
           1       0.75      0.96      0.84        25

    accuracy                           0.84        56
   macro avg       0.85      0.85      0.84        56
weighted avg       0.87      0.84      0.84        56



Even though there is almost a tie between Logistic regression and Random forest model but we will still go with Random forest model since it is more reliable.